
export const airportList = [
  // 🌍 Africa
  "Murtala Muhammed International Airport (LOS) - Lagos, Nigeria",
  "Nnamdi Azikiwe International Airport (ABV) - Abuja, Nigeria",
  "Mallam Aminu Kano International Airport (KAN) - Kano, Nigeria",
  "Port Harcourt International Airport (PHC) - Port Harcourt, Nigeria",
  "Kotoka International Airport (ACC) - Accra, Ghana",
  "O.R. Tambo International Airport (JNB) - Johannesburg, South Africa",
  "Cape Town International Airport (CPT) - Cape Town, South Africa",
  "Cairo International Airport (CAI) - Cairo, Egypt",
  "Addis Ababa Bole International Airport (ADD) - Addis Ababa, Ethiopia",
  "Nairobi Jomo Kenyatta International Airport (NBO) - Nairobi, Kenya",
  "Mohammed V International Airport (CMN) - Casablanca, Morocco",
  "Houari Boumédiène Airport (ALG) - Algiers, Algeria",
  "Tunis–Carthage International Airport (TUN) - Tunis, Tunisia",
  "Sir Seewoosagur Ramgoolam International Airport (MRU) - Port Louis, Mauritius",
  "Sihlangu King Mswati III International Airport (SID) - Manzini, Eswatini",
  "Léopold Sédar Senghor International Airport (DKR) - Dakar, Senegal",
  "Juba International Airport (JUB) - Juba, South Sudan",
  "Lomé–Tokoin International Airport (LFW) - Lomé, Togo",

  // 🌍 Europe
  "Heathrow Airport (LHR) - London, UK",
  "Gatwick Airport (LGW) - London, UK",
  "Manchester Airport (MAN) - Manchester, UK",
  "Charles de Gaulle Airport (CDG) - Paris, France",
  "Orly Airport (ORY) - Paris, France",
  "Frankfurt Airport (FRA) - Frankfurt, Germany",
  "Munich Airport (MUC) - Munich, Germany",
  "Schiphol Airport (AMS) - Amsterdam, Netherlands",
  "Zurich Airport (ZRH) - Zurich, Switzerland",
  "Madrid–Barajas Adolfo Suárez Airport (MAD) - Madrid, Spain",
  "Barcelona–El Prat Airport (BCN) - Barcelona, Spain",
  "Leonardo da Vinci–Fiumicino Airport (FCO) - Rome, Italy",
  "Milan Malpensa Airport (MXP) - Milan, Italy",
  "Vienna International Airport (VIE) - Vienna, Austria",
  "Istanbul Airport (IST) - Istanbul, Türkiye",
  "Dublin Airport (DUB) - Dublin, Ireland",
  "Lisbon Airport (LIS) - Lisbon, Portugal",
  "Copenhagen Airport (CPH) - Copenhagen, Denmark",
  "Oslo Airport, Gardermoen (OSL) - Oslo, Norway",
  "Stockholm Arlanda Airport (ARN) - Stockholm, Sweden",
  "Helsinki Airport (HEL) - Helsinki, Finland",
  "Warsaw Chopin Airport (WAW) - Warsaw, Poland",
  "Prague Václav Havel Airport (PRG) - Prague, Czech Republic",
  "Budapest Ferenc Liszt International Airport (BUD) - Budapest, Hungary",
  "Athens International Airport (ATH) - Athens, Greece",
  "Brussels Airport (BRU) - Brussels, Belgium",
  "Moscow Sheremetyevo International Airport (SVO) - Moscow, Russia",
  "Geneva Airport (GVA) - Geneva, Switzerland",
  "Düsseldorf Airport (DUS) - Düsseldorf, Germany",

  // 🌍 Middle East
  "Dubai International Airport (DXB) - Dubai, UAE",
  "Abu Dhabi International Airport (AUH) - Abu Dhabi, UAE",
  "Doha Hamad International Airport (DOH) - Doha, Qatar",
  "King Abdulaziz International Airport (JED) - Jeddah, Saudi Arabia",
  "King Khalid International Airport (RUH) - Riyadh, Saudi Arabia",
  "Queen Alia International Airport (AMM) - Amman, Jordan",
  "Beirut–Rafic Hariri International Airport (BEY) - Beirut, Lebanon",
  "Muscat International Airport (MCT) - Muscat, Oman",
  "Bahrain International Airport (BAH) - Manama, Bahrain",
  "Ben Gurion Airport (TLV) - Tel Aviv, Israel",
  "Kuwait International Airport (KWI) - Kuwait City, Kuwait",

  // 🌍 Asia
  "Beijing Capital International Airport (PEK) - Beijing, China",
  "Shanghai Pudong International Airport (PVG) - Shanghai, China",
  "Hong Kong International Airport (HKG) - Hong Kong",
  "Tokyo Haneda Airport (HND) - Tokyo, Japan",
  "Narita International Airport (NRT) - Tokyo, Japan",
  "Incheon International Airport (ICN) - Seoul, South Korea",
  "Singapore Changi Airport (SIN) - Singapore",
  "Kuala Lumpur International Airport (KUL) - Kuala Lumpur, Malaysia",
  "Indira Gandhi International Airport (DEL) - Delhi, India",
  "Chhatrapati Shivaji Maharaj International Airport (BOM) - Mumbai, India",
  "Bangkok Suvarnabhumi Airport (BKK) - Bangkok, Thailand",
  "Manila Ninoy Aquino International Airport (MNL) - Manila, Philippines",
  "Guangzhou Baiyun International Airport (CAN) - Guangzhou, China",
  "Shanghai Hongqiao International Airport (SHA) - Shanghai, China",
  "Seoul Gimpo International Airport (GMP) - Seoul, South Korea",
  "Kaohsiung International Airport (KHH) - Kaohsiung, Taiwan",
  "Taiwan Taoyuan International Airport (TPE) - Taipei, Taiwan",
  "Tan Son Nhat International Airport (SGN) - Ho Chi Minh City, Vietnam",
  "Noi Bai International Airport (HAN) - Hanoi, Vietnam",
  "Netaji Subhas Chandra Bose International Airport (CCU) - Kolkata, India",
  "Kempegowda International Airport (BLR) - Bengaluru, India",
  "Soekarno–Hatta International Airport (CGK) - Jakarta, Indonesia",
  "Bandaranaike International Airport (CMB) - Colombo, Sri Lanka",
  "Islamabad International Airport (ISB) - Islamabad, Pakistan",
  "Tribhuvan International Airport (KTM) - Kathmandu, Nepal",
  "Male Velana International Airport (MLE) - Malé, Maldives",
  "Almaty International Airport (ALA) - Almaty, Kazakhstan",

  // 🌍 Oceania
  "Sydney Kingsford Smith Airport (SYD) - Sydney, Australia",
  "Melbourne Tullamarine Airport (MEL) - Melbourne, Australia",
  "Brisbane Airport (BNE) - Brisbane, Australia",
  "Auckland Airport (AKL) - Auckland, New Zealand",
  "Perth Airport (PER) - Perth, Australia",
  "Adelaide Airport (ADL) - Adelaide, Australia",
  "Cairns Airport (CNS) - Cairns, Australia",
  "Christchurch Airport (CHC) - Christchurch, New Zealand",
  "Wellington Airport (WLG) - Wellington, New Zealand",
  "Fiji Nadi International Airport (NAN) - Nadi, Fiji",

  // 🌍 North America
  "John F. Kennedy International Airport (JFK) - New York, USA",
  "LaGuardia Airport (LGA) - New York, USA",
  "Newark Liberty International Airport (EWR) - Newark, USA",
  "Los Angeles International Airport (LAX) - Los Angeles, USA",
  "San Francisco International Airport (SFO) - San Francisco, USA",
  "Chicago O'Hare International Airport (ORD) - Chicago, USA",
  "Hartsfield–Jackson Atlanta International Airport (ATL) - Atlanta, USA",
  "Miami International Airport (MIA) - Miami, USA",
  "Dallas/Fort Worth International Airport (DFW) - Dallas, USA",
  "Toronto Pearson International Airport (YYZ) - Toronto, Canada",
  "Vancouver International Airport (YVR) - Vancouver, Canada",
  "Montréal–Trudeau International Airport (YUL) - Montreal, Canada",
  "Mexico City International Airport (MEX) - Mexico City, Mexico",
  "Denver International Airport (DEN) - Denver, USA",
  "Las Vegas Harry Reid International Airport (LAS) - Las Vegas, USA",
  "Orlando International Airport (MCO) - Orlando, USA",
  "Seattle–Tacoma International Airport (SEA) - Seattle, USA",
  "Charlotte Douglas International Airport (CLT) - Charlotte, USA",
  "Phoenix Sky Harbor International Airport (PHX) - Phoenix, USA",
  "Washington Dulles International Airport (IAD) - Washington D.C., USA",
  "Ronald Reagan Washington National Airport (DCA) - Washington D.C., USA",
  "Baltimore/Washington International Thurgood Marshall Airport (BWI) - Baltimore, USA",
  "Boston Logan International Airport (BOS) - Boston, USA",
  "Philadelphia International Airport (PHL) - Philadelphia, USA",
  "Minneapolis–Saint Paul International Airport (MSP) - Minneapolis, USA",
  "Detroit Metropolitan Wayne County Airport (DTW) - Detroit, USA",
  "George Bush Intercontinental Airport (IAH) - Houston, USA",
  "Cancún International Airport (CUN) - Cancún, Mexico",
  "Guadalajara International Airport (GDL) - Guadalajara, Mexico",
  "Punta Cana International Airport (PUJ) - Punta Cana, Dominican Republic",
  "Norman Manley International Airport (KIN) - Kingston, Jamaica",
  "José Martí International Airport (HAV) - Havana, Cuba",

  // 🌍 South America
  "São Paulo–Guarulhos International Airport (GRU) - São Paulo, Brazil",
  "Rio de Janeiro–Galeão International Airport (GIG) - Rio de Janeiro, Brazil",
  "Buenos Aires Ministro Pistarini International Airport (EZE) - Buenos Aires, Argentina",
  "Lima Jorge Chávez International Airport (LIM) - Lima, Peru",
  "Bogotá El Dorado International Airport (BOG) - Bogotá, Colombia",
  "Santiago Arturo Merino Benítez International Airport (SCL) - Santiago, Chile",
  "Mariscal Sucre International Airport (UIO) - Quito, Ecuador",
  "Jorge Wilstermann International Airport (CBB) - Cochabamba, Bolivia",
  "Simón Bolívar International Airport (CCS) - Caracas, Venezuela",
  "Carrasco International Airport (MVD) - Montevideo, Uruguay",
  "Silvio Pettirossi International Airport (ASU) - Asunción, Paraguay",
  "Ezeiza International Airport (EZE) - Buenos Aires, Argentina",
];






